POST http://127.0.0.1:3000/user
client-version: 0.1.0
Authorization: 0
Content-Type: application/json

{
  "username": "user",
  "password_hash": "password"
}

###

POST 127.0.0.1:3000/generate_session
client-version: 0.1.0
Authorization: 0734fc36-a59c-4528-bfd5-0c9d42c21eaf
