#@name create_user
POST http://127.0.0.1:3000/user
client-version: 0.1.0
Content-Type: application/json

{
  "email": "example@gmail.com",
  "username": "user",
  "password": "password"
}

###

#@name login
POST 127.0.0.1:3000/login
client-version: 0.1.0
Content-Type: application/json

{
  "account_identifier": {"username": "user" },
  "password": "password"
}