//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "item_model")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub item_model_id: Uuid,
	pub name: String,
	pub description: Option<String>,
	pub permission_level: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
