//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "item")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub item_id: Uuid,
	pub name: String,
	pub item_model_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::borrow::Entity")]
	Borrow,
	#[sea_orm(
		belongs_to = "super::item_model::Entity",
		from = "Column::ItemModelId",
		to = "super::item_model::Column::ItemModelId",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	ItemModel,
}

impl Related<super::borrow::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Borrow.def()
	}
}

impl Related<super::item_model::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ItemModel.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
