//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "session")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub session_id: Uuid,
	pub user_id:    Uuid,
	pub created_at: DateTimeWithTimeZone,
	pub expired:    bool
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::UserId",
		to = "super::user::Column::UserId",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	User
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef { Relation::User.def() }
}

impl ActiveModelBehavior for ActiveModel {}
