//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub user_id:          Uuid,
	#[sea_orm(unique)]
	pub username:         String,
	#[sea_orm(unique)]
	pub email:            String,
	pub password:         String,
	pub permission_level: String,
	pub created_at:       DateTimeWithTimeZone
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::session::Entity")]
	Session
}

impl Related<super::session::Entity> for Entity {
	fn to() -> RelationDef { Relation::Session.def() }
}

impl ActiveModelBehavior for ActiveModel {}
